api_platform:
    title: API
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        pagination_enabled: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
